import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FCFCFC",
    alignItems: "center",
    justifyContent: "center",
    // marginTop: "-10%",
  },
  containerMargin: {
    flex: 1,
    backgroundColor: "#FCFCFC",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "-12%",
  },
  dishWrap: {
    flex: 1,
    backgroundColor: "#F6F7F7",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 24,
    height: "100%",
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  textWrap: {
    textAlign: "center",
    paddingBottom: "16%",
  },
  wrap: {
    flex: 1,
    width: "90%",
    alignItems: "flex-start",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  inner: {
    flex: 2,
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  bottom: {
    flex: 2,
    width: "88%",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  headerLogin: {
    width: "80%",
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "flex-end",
    flexDirection: "column",
    zIndex: 999,
    marginLeft: "8%",
    marginTop: "16%",
  },
  innerLogin: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    marginTop: "8%",
  },
  bottomLogin: {
    flex: 1.5,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    marginTop: "24%",
    paddingTop: "8%",
  },
  headerInfo: {
    width: "88%",
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "flex-end",
    flexDirection: "column",
    zIndex: 999,
    marginTop: "16%",
  },
  innerFirstInfor: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    marginTop: "8%",
    // borderWidth: 4,
    // borderColor: '#24B445',
    // borderStyle: "solid",
  },
  innerFirstInforImg: {
    borderWidth: 4,
    borderColor: "#24B445",
    borderStyle: "solid",
    padding: 8,
    borderRadius: 100,
    zIndex: -1,
  },
  innerSecondInfor: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    marginTop: "16%",
    paddingTop: "8%",
  },
  innerThirdInfor: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    flexDirection: "column",
    marginTop: 24,
  },
  bottomInfor: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
  },
  headerSetting: {
    flex: 1,
    width: "88%",
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "column",
    textAlign: "center",
    marginTop: "8%"
  },
  innerSetting: {
    flex: 1,
    width: "80%",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    marginBottom: "8%"
  },
  bottomSetting: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    marginTop: 24,
  },

  innerSettingAge: {
    paddingTop: 60,
    paddingBottom: 30,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  wrapperVertical: {
    width: 250,
    height: 300,
    justifyContent: "center",
    alignItems: "center",
    margin: "auto",
    color: "black",
  },
  OptionWrapper: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 10,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 30,
    paddingRight: 30,
    height: 50,
    borderWidth: 3,
    borderRadius: 10,
  },

  headerAnalysis: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    textAlign: "center",
  },
  innerAnalysis: {
    flex: 1,
    width: "80%",
    alignItems: "center",
    justifyContent: "flex-start",
    textAlign: "center",
  },

  headerAnalysisBMI: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    textAlign: "left",
    width: "100%",
  },
  innerAnalysisBMI: {
    flex: 3,
    backgroundColor: "rgba(246, 247, 247, 0.9)",
    alignItems: "center",
    justifyContent: "flex-start",
    textAlign: "center",
    borderColor: "#F6F7F7",
    borderWidth: 4,
    width: "100%",
    padding: "8%",
    borderRadius: 32,
  },

  headerPayment: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    textAlign: "left",
    width: "100%",
  },
  innerPayment: {
    flex: 3,
    backgroundColor: "rgba(36, 180, 69, 0.8)",
    alignItems: "center",
    justifyContent: "flex-start",
    textAlign: "center",
    width: "100%",
    padding: "8%",
    borderRadius: 32,
  },

  headerDailyMenu: {
    flex: 0.5,
    alignItems: "flex-end",
    justifyContent: "space-between",
    width: "92%",
    flexDirection: "row",
  },
  headerDailyMenuIcon: {
    flexDirection: "row",
  },
  innerDailyMenu: {
    flex: 0.5,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    flexDirection: "row",
    width: "100%",
  },
  innerSubDailyMenu: {
    flex: 0.25,
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    width: "100%",
    padding: 8,
    borderTopColor: "#DEDEDE",
    borderBottomColor: "#DEDEDE",
    borderTopWidth: 1,
    borderBottomWidth: 1,
  },

  innerSubDailyText: {
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    width: "100%",
    padding: 8,
  },

  innerSubDailyDish: {
    height: 200,
    alignItems: "flex-start",
    justifyContent: "flex-end",
    flexDirection: "column",
    width: "88%",
    backgroundColor: "#FFF",
    marginBottom: 16,
    borderRadius: 16,
    overflow: "hidden",
    paddingLeft: 24,
    paddingBottom: 24,
    marginLeft: 12,
  },

  innerSubDailyDishTextBorder: {
    borderBottomColor: "rgba(0, 0, 0, 0.07)",
    borderBottomWidth: 1,
    paddingBottom: 8,
  },

  innerSubDailyTextBorder: {
    borderBottomColor: "#FF6810",
    borderBottomWidth: 2,
    position: "absolute",
    zIndex: 999,
    width: 120,
    top: 20,
    left: 32,
  },

  innerDailyMenuCalendar: {
    width: "100%",
    height: 100,
    paddingTop: 20,
    paddingBottom: 10,
  },

  bottomDailyMenuCalendar: {
    flex: 3,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F9F9F9",
    width: "96%",
  },

  headerMeal: {
    flex: 0.5,
    alignItems: "center",
    width: "88%",
    flexDirection: "row",
    marginTop: 48,
  },

  innerMeal: {
    flex: 1.5,
    alignItems: "flex-start",
    width: "100%",
  },

  bottomMeal: {
    flex: 4,
    alignItems: "center",
    width: "100%",
    backgroundColor: "#FFF",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.37,
    shadowRadius: 7.49,
    elevation: 12,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  innerBottomMealContainerFlex: {
    justifyContent: "flex-start",
    width: "80%",
    height: 320,
    marginTop: 24,
    flex: 2
  },
  innerBottomMealContainer: {
    justifyContent: "flex-start",
    width: "80%",
    height: 320,
    marginTop: 24,
  },
  innerBottomMeal: {
    justifyContent: "space-between",
    flexDirection: "row",
  },

  innerBottomMealStepContainer: {
    justifyContent: "center",
    width: "64%",
    flexDirection: "row",
  },

  innerBottomMealButton: {
    justifyContent: "center",
    flexDirection: "row",
    width: "100%",
  },

  headerNoti: {
    flex: 0.5,
    alignItems: "flex-end",
    justifyContent: "space-between",
    width: "88%",
    flexDirection: "row",
    marginTop: 24,
  },
  subHeaderNoti: {
    flex: 0.25,
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
    flexDirection: "row",
    marginTop: 32,
  },
  innerNoti: {
    flex: 5,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "96%",
    flexDirection: "column",
  },
  innerNotiInfo: {
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  innerNotiInfoText: {
    borderBottomColor: "rgba(0, 0, 0, 0.1)",
    borderBottomWidth: 1,
    width: "64%",
    paddingBottom: 16,
    paddingTop: 16,
    paddingLeft: 8,
  },

  innerTipsContainer: {
    flex: 4.5,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    flexDirection: "column",
    marginTop: "8%",
  },

  subHeaderTips: {
    flex: 1.5,
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
    flexDirection: "row",
  },
  innerTips: {
    flex: 3.5,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "88%",
    marginLeft: "6%",
    flexDirection: "column",
    marginBottom: "8%",
    marginTop: "4%",
  },

  headerAnalysisHome: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "100%",
  },
  subHeaderAnalysisHome: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    top: "40%",
    left: "8%",
    width: "52%",
  },

  innerAnalysisHome: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    flexDirection: "column",
  },

  bottomAnalysisHome: {
    flex: 3.5,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    flexDirection: "column",
  },
  bottomDateAnalysisHome: {
    alignItems: "flex-start",
    justifyContent: "space-between",
    width: "92%",
    alignSelf: "center",
    flexDirection: "row",
    backgroundColor: "rgba(36, 180, 69, 0.5)",
    borderRadius: 4,
  },

  innerAnalysisHomeWeightContainerBox: {
    width: "100%",
    backgroundColor: "#FFF",
    marginTop: 8,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },

  innerAnalysisHomeCaloriesContainerBox: {
    width: "92%",
    backgroundColor: "#FFF",
    marginTop: 8,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    alignSelf: "center",
    marginBottom: 36,
    overflow: "hidden",
  },

  innerAnalysisHomeCaloriesContainerBoxColumn: {
    width: "92%",
    marginTop: 8,
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 36,
    flexDirection: "row",
    alignSelf: "center"
  },

  innerAnalysisHomeCaloriesBoxColumn: {
    width: "48%",
    backgroundColor: "#FFF",
    padding: 16,
    marginTop: -16,
    borderRadius: 32,
    shadowColor: "#000",
    overflow:"hidden",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    alignSelf: "center",
  },

  innerAnalysisHomeWeightContainer: {
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "92%",
    backgroundColor: "#FFF",
    marginTop: 8,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#CDCDCD",
    alignSelf: "center",
    paddingBottom: 8,
  },

  bottomWeightAnalysisHome: {
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "92%",
    alignSelf: "center",
  },

  headerHomeInformation: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "100%",
  },
  subHeaderHomeInformation: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    top: "48%",
    left: "8%",
    width: "56%",
  },

  innerHomeInformation: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    flexDirection: "column",
    marginTop: 36,
    marginBottom: 56,
  },

  bottomHomeInformation: {
    flex: 3.5,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "88%",
    flexDirection: "column",
  },
  bottomHomeInformationPlan: {
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    width: "100%",
    flexDirection: "row",
    backgroundColor: "rgba(36, 180, 69, 1)",
    padding: 16,
    borderRadius: 16,
  },

  bottomHomeInformationSettingsContainer: {
    width: "100%",
    flexDirection: "column",
    padding: 16,
    borderColor: "rgba(0, 0, 0, 0.2)",
    borderWidth: 1,
    borderRadius: 16,
    backgroundColor: "#FFF",
  },
  bottomHomeInformationSettings: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
  },

  headerEditInformation: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "100%",
  },
  subHeaderEditInformation: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    top: "48%",
    left: "8%",
    width: "70%",
  },

  innerEditInformation: {
    flex: 5,
    alignItems: "center",
    justifyContent: "flex-start",
    width: "96%",
    flexDirection: "column",
    marginTop: -16,
  },
  innerEditInformationInput: {
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "96%",
    flexDirection: "column",
    padding: 8,
    borderRadius: 12,
    paddingLeft: 16,
  },

  innerEditInformationInputProDis: {
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "96%",
    flexDirection: "row",
    padding: 8,
    borderRadius: 12,
    paddingLeft: 16,
  },

  innerEditInformationInputCalendar: {
    flexDirection: "row",
    borderRadius: 12,
    backgroundColor: "rgba(36, 180, 69, 0.2)",
    borderRadius: 8,
    height: 40,
    width: "96%",
    paddingLeft: 16,
    alignItems: "center",
    justifyContent: "space-between",
    paddingRight: 8,
  },

  innerEditInformationTextInput: {
    borderRadius: 12,
    backgroundColor: "rgba(36, 180, 69, 0.2)",
    borderRadius: 8,
    height: 40,
    width: "96%",
    paddingLeft: 16,
  },

  modalAnalysisHomeContainer: {
    alignSelf: "center",
    backgroundColor: "rgba(36, 180, 69, 0.2)",
    borderRadius: 8,
    width: "88%",
    backgroundColor: "#FFF",
    padding: 16,
  },
  modalAnalysisHomeWeight: {
    alignSelf: "center",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(36, 180, 69, 0.8)",
    width: "96%",
    backgroundColor: "#FFF",
    padding: 4,
    paddingLeft: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalAnalysisHomeWeightText: {
    borderRadius: 24,
    backgroundColor: "#276047",
    padding: 8,
    width: "24%",
    textAlign: "center",
    color: "#FFF",
  },

  innerAnalysisWeekWeight: {
    position: "absolute",
    alignSelf: "center",
    alignItems: "center",
    top: 24,
    bottom: 0,
    justifyContent: "center"
  }
});
export default styles;
